name: Publish to npm

on:
  # Trigger the workflow whenever a new tag is pushed
  push:
    tags:
      - 'v*' # Only trigger for tags matching the "v*" pattern, e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use any Node.js version compatible with your project
        registry-url: 'https://registry.npmjs.org'

    # Step 3: Install dependencies (if needed, optional)
    - name: Install dependencies
      run: npm install

    # Step 4: Publish the package to npm
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the npm token stored as a GitHub secret
